apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository-traefik.yaml
  - helmrelease-traefik.yaml
  - helmrepository-certmanager.yaml
  - helmrelease-certmanager.yaml
